In [1]:
 import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([(1.5,2,3), (4,5,6)]),
print(b)

(array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]]),)


In [4]:
 c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]]),
print(c)

(array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]]),)


In [5]:
np.save("my_array", a)

In [6]:
np.savez('array.npz', a, b)

In [7]:
np.load('my_array.npy')

array([1, 2, 3])

In [8]:
np.save("myfile.txt", a)

In [9]:
np.load("myfile.txt.npy")

array([1, 2, 3])

In [10]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [11]:
a.shape

(3,)

In [12]:
len(a)

3

In [13]:
a.ndim

1

In [14]:
a.size

3

In [15]:
 g = a - b

In [16]:
print(g)

[[[-0.5  0.   0. ]
  [-3.  -3.  -3. ]]]


In [17]:
h = a + b
print(h)

[[[2.5 4.  6. ]
  [5.  7.  9. ]]]


In [18]:
w = a * b
print(w)

[[[ 1.5  4.   9. ]
  [ 4.  10.  18. ]]]


In [19]:
r = a/b
print (r)

[[[0.66666667 1.         1.        ]
  [0.25       0.4        0.5       ]]]


In [20]:
a.sum()

6

In [21]:
a.min()

1

In [22]:
a.max(axis=0)

3

In [23]:
a.mean()

2.0

In [24]:
np.median(a)

2.0

In [25]:
np.std(b)

1.5920810978785667

In [26]:
h = a. view

In [27]:
print(h)

<built-in method view of numpy.ndarray object at 0x000002D0053418F0>


In [28]:
np.copy(a)

array([1, 2, 3])

In [29]:
h = a.copy()

In [30]:
a.sort()

In [31]:
a.sort(axis=0)

In [32]:
a[2]

3

In [33]:
b[0]

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [34]:
h.resize((2,6))

In [35]:
print(h)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [36]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [37]:
np.delete(a,[1])

array([1, 3])

In [38]:
## SHAMSHER ALI